name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    env:
      TO_SEARCH: "/assets/"
      NEXTJS_BACKEND_URL: "/action-publish-test"
      GHP_ROOT: ${{ env.NEXTJS_BACKEND_URL }}
      TO_REPLACE: ${{ env.GHP_ROOT+''+env.TO_SEARCH }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install

      - name: revise assets
        run: |
          set -x

          post_filenames=$(find ./_posts -iname '*.md')

          # search
          echo ${post_filenames} | xargs \
          grep -H ${TO_SEARCH}

          # replace
          echo ${post_filenames} | xargs \
          sed -i s#${TO_SEARCH}#${TO_REPLACE}#g

          # verify
          echo ${post_filenames} | xargs \
          grep -H ${TO_REPLACE}

      - name: revise link
        run: |
          from_import="import Link from 'next/link'"
          to_import="import Link from './link'"

          comp_filenames=$(find ./components -iname '*.js')

          echo ${comp_filenames} | xargs \
          sed -i "s#${from_import}#${to_import}#g"

      - name: inject link comp
        run: |
          cat <<-EOF > components/link.ts
          import NextLink, { LinkProps } from 'next/link'
          import { format } from 'url'

          const basePath = "${GHP_ROOT}";

          const Link: React.FunctionComponent<LinkProps> = ({ children, ...props }) => (
            <NextLink
              {...props}
              as={\`\${basePath || ''}\${format(props.href)}\`}
            >
              {children}
            </NextLink>
          )

          export default Link
          EOF

      - run: yarn build
        env:

      - run: yarn export
        env:

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.5.7
        with:
          user_name: ${{ secrets.GHP_PUBLISH_USERNAME }}
          user_email: ${{ secrets.GHP_PUBLISH_EMAIL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
